# aws cloudformation deploy --template-file backend-infrastructure.yml --stack-name llmc-infra-nonprod --parameter-overrides AppName=llmcouncil Environment=nonprod --capabilities CAPABILITY_NAMED_IAM
AWSTemplateFormatVersion: '2010-09-09'
Description: The AWS infrastructure resources for llm council.
Parameters:
  AppName:
    Description: The name of the application; Used to generate resource names.
    Type: String
  Environment:
    Description: The environment of the application.
    Type: String
    AllowedValues:
      - nonprod
      - prod
Resources:
  BuildExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LLMCInfraRole
      Description: Role required to manage create the llm council infra.
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LLMCouncilExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ecs-tasks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      Policies:
        -
          PolicyName: "fargate-service"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "ecr:Get*"
                  - "ecr:BatchGetImage"
                  - "ecr:BatchCheckLayerAvailability"
                  - "logs:CreateLog*"
                  - "logs:PutLogEvents"
                  - "kms:GenerateDataKey"
                  - "kms:Decrypt"
                Resource: "*"

  TheSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AppName}-${Environment}'
      Description: !Sub "Secrets for ${AppName} ${Environment}"
      SecretString: |
        { 
          "apiKey": "",
          "apiBaseUrl": "",
          "npmToken": ""
        }

  GitHubActionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AppName}-github-role-${Environment}'
      Tags:
        - Key: ghaoidc
          Value: "true"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: repo:bayer-int/llmcouncil:*
          - Effect: Allow
            Action: sts:TagSession
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Condition:
              ForAllValues:StringLike:
                aws:TagKeys: gha_*
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
      Policies:
        - PolicyName: !Sub "${AppName}-policies"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:*'
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:ListBucket
                  - s3:DeleteObject
                  - s3:ListObjectsV2
                Resource:
                  - !Sub "arn:aws:s3:::${AppName}-${Environment}*"
              - Effect: Allow
                Action:
                  - cloudfront:CreateInvalidation
                Resource:
                - !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/*"
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                Resource:
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*"

